using System;
using System.IO;
using System.Reflection;
using System.Diagnostics;
using System.Text;
using System.Collections.Generic;
using UnityEngine;
using DCFApixels.WhimTex;
using Object=UnityEngine.Object;
public static class SeamlessOptimizationTests
{
    const BindingFlags F=BindingFlags.Static|BindingFlags.NonPublic|BindingFlags.Public;
    static RenderTexture Render(Texture t,int mode,int edges=0,float strength=1)
    {
        var a=typeof(WhimTexDocument).Assembly;
        object Call(string type,string method,params object[] args)=>a.GetType("DCFApixels.WhimTex."+type).GetMethod(method,F).Invoke(null,args);
        var pair=(MakeSeamlessLayerBehaviour.PoissonEdges)edges;
        var mask=edges==0?Vector4.one:edges==1?new Vector4(0,0,1,1):new Vector4(1,1,0,0);
        if(mode==0)return (RenderTexture)Call("HistogramSeamless","RenderMirror",t,t.width,t.height,mask,.2f,1f,strength);
        if(mode==1)return (RenderTexture)Call("HistogramSeamless","RenderOffset",t,t.width,t.height,mask,.2f,strength,false,0f,pair,-.25f);
        if(mode==2)return (RenderTexture)Call("ScreenedSeamless","RenderConfigured",t,t.width,t.height,pair,.05f);
        return (RenderTexture)Call("PatchQuiltingSeamless","RenderCompensated",t,t.width,t.height,pair,.2f,100f,
            MakeSeamlessLayerBehaviour.QuiltingQuality.High,73,MakeSeamlessLayerBehaviour.QuiltingChannels.Independent,Vector4.one,strength);
    }
    static Color[] Pixels(RenderTexture rt,Texture2D read)
    {var old=RenderTexture.active;try{RenderTexture.active=rt;read.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0,false);return read.GetPixels();}finally{RenderTexture.active=old;}}
    static Texture2D Source(int w,int h,int fixture)
    {
        var t=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Own(new Texture2D(w,h,TextureFormat.RGBAFloat,false,true));var pixels=new Color[w*h];var random=new System.Random(55);
        for(int y=0;y<h;y++)for(int x=0;x<w;x++)
        {
            float v=.4f+.25f*Mathf.Sin(x*.061f+y*.071f)+.2f*Mathf.Cos(x*.143f-y*.097f);
            pixels[y*w+x]=fixture==0?new Color(v,v,v,1):fixture==1?new Color(v*2,(float)random.NextDouble()-.3f,1-v,x%13==0?0:(float)random.NextDouble()):new Color(-.1f,2,.7f,.4f);
        }
        t.SetPixels(pixels);t.Apply(false,false);return t;
    }
    // Port of the original assertion-free pixel producer plus its caller-state guard.
    // The parent must supply a separately reviewed pre-change renderer; current Render is never used.
    // Generated bytes are diagnostic artifacts, never automatically registered as a comparison oracle.
    public static string CaptureHistorical(Func<Texture,int,int,float,RenderTexture> reviewedHistoricalRender)
        => global::WhimTex.Tests.UnityC.FixtureContext.Diagnostic("SeamlessOptimizationTests.CaptureHistorical", () =>
        {
            if (reviewedHistoricalRender == null) throw new ArgumentNullException(nameof(reviewedHistoricalRender));
            string folder=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Temp;int count=0;
            foreach(var size in new[]{new Vector2Int(1,7),new Vector2Int(17,13),new Vector2Int(64,48),new Vector2Int(65,63)})
            for(int fixture=0;fixture<3;fixture++)
            {
                var t=Source(size.x,size.y,fixture);var read=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Own(new Texture2D(size.x,size.y,TextureFormat.RGBAFloat,false,true));
                try{for(int mode=0;mode<4;mode++)for(int edge=0;edge<3;edge++)foreach(float strength in new[]{0f,1f})
                {
                    if(mode==2&&strength==0)continue;
                    string path=Path.Combine(folder,$"{size.x}-{size.y}-{fixture}-{mode}-{edge}-{(int)strength}.bin");
                    var old=RenderTexture.active;bool srgb=GL.sRGBWrite;
                    var rt=reviewedHistoricalRender(t,mode,edge,strength);Color[] pixels;
                    try{pixels=Pixels(rt,read);}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Release(rt);}
                    global::WhimTex.Tests.UnityC.FixtureContext.Context.True(!(RenderTexture.active!=old||GL.sRGBWrite!=srgb), "Caller render state");
                    using(var writer=new BinaryWriter(File.Create(path)))foreach(var p in pixels)for(int c=0;c<4;c++)writer.Write(p[c]);
                    count++;
                }}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(t);global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(read);}
            }
            return $"Captured {count} historical-renderer diagnostic fixtures in owned output. Separate path/hash/provenance review is required before using any artifact as an oracle.";
        });
    static string Fixtures(Dictionary<string, byte[]> snapshots,bool audit=false)
    {
        int count=0;double max=0;var differences=new double[4];
        foreach(var size in new[]{new Vector2Int(1,7),new Vector2Int(17,13),new Vector2Int(64,48),new Vector2Int(65,63)})
        for(int fixture=0;fixture<3;fixture++)
        {
            var t=Source(size.x,size.y,fixture);var read=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Own(new Texture2D(size.x,size.y,TextureFormat.RGBAFloat,false,true));
            try{for(int mode=0;mode<4;mode++)for(int edge=0;edge<3;edge++)foreach(float strength in new[]{0f,1f})
            {
                if(mode==2&&strength==0)continue;
                string path=$"{size.x}-{size.y}-{fixture}-{mode}-{edge}-{(int)strength}.bin";
                var old=RenderTexture.active;bool srgb=GL.sRGBWrite;var rt=Render(t,mode,edge,strength);Color[] pixels;
                try{pixels=Pixels(rt,read);}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Release(rt);}
                global::WhimTex.Tests.UnityC.FixtureContext.Context.True(!(RenderTexture.active!=old||GL.sRGBWrite!=srgb), "Caller render state");
                using(var reader=new BinaryReader(new MemoryStream(snapshots[path],false)))foreach(var p in pixels)for(int c=0;c<4;c++)
                {
                    float expected=reader.ReadSingle();double delta=Math.Abs(p[c]-expected);max=Math.Max(delta,max);
                    differences[mode]=Math.Max(differences[mode],delta);
                    global::WhimTex.Tests.UnityC.FixtureContext.Context.True(float.IsFinite(expected), "Finite original snapshot value: "+path);
                    global::WhimTex.Tests.UnityC.FixtureContext.Context.True(!(!float.IsFinite(p[c])||(!audit&&delta>2e-5)), $"Mismatch {path}: {p[c]} vs {expected}, delta {delta}");
                }
                count++;
            }}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(t);global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(read);}
        }
        return $"Compared {count} fixtures; max absolute difference {max:R}; modes {string.Join(", ",differences)}.";
    }
    static string ExecutePairedPoisson()
    {
        var t=Source(512,512,1);var read=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Own(new Texture2D(512,512,TextureFormat.RGBAFloat,false,true));var report=new StringBuilder();
        try{for(int edge=0;edge<3;edge++)
        {
            var times=new double[2][] {new double[15],new double[15]};Color[] original=null;
            for(int i=-3;i<15;i++)for(int pass=0;pass<2;pass++)
            {
                int version=(pass+(i&1))%2;var timer=Stopwatch.StartNew();
                var rt=version==0?ScreenedOptimizationBaseline.RenderConfigured(t,512,512,(MakeSeamlessLayerBehaviour.PoissonEdges)edge,.05f):Render(t,2,edge);
                try{var pixels=Pixels(rt,read);timer.Stop();if(i>=0)times[version][i]=timer.Elapsed.TotalMilliseconds;
                    if(i==0){if(version==0)original=pixels;else if(original!=null)for(int j=0;j<pixels.Length;j++)for(int c=0;c<4;c++)global::WhimTex.Tests.UnityC.FixtureContext.Context.True(!(pixels[j][c]!=original[j][c]), "Paired Poisson differs");}}
                finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Release(rt);}
            }
            Array.Sort(times[0]);Array.Sort(times[1]);report.AppendLine($"edge {edge}: baseline {times[0][7]:F3} ms -> current {times[1][7]:F3} ms");
        }}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(t);global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(read);}
        return report.ToString();
    }
    static string ExecuteBenchmark()
    {
        var report=new StringBuilder("512x512, warm medians, 9 samples, final GPU readback included\n");
        var t=Source(512,512,1);var read=global::WhimTex.Tests.UnityC.FixtureContext.Scope.Own(new Texture2D(512,512,TextureFormat.RGBAFloat,false,true));
        try{for(int mode=0;mode<4;mode++)foreach(float strength in new[]{0f,1f})
        {
            if(mode==2&&strength==0)continue;
            var times=new double[9];
            for(int i=-3;i<9;i++)
            {
                var watch=Stopwatch.StartNew();var rt=Render(t,mode,0,strength);
                try{var old=RenderTexture.active;try{RenderTexture.active=rt;read.ReadPixels(new Rect(0,0,512,512),0,0,false);}finally{RenderTexture.active=old;}}
                finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Release(rt);}
                watch.Stop();if(i>=0)times[i]=watch.Elapsed.TotalMilliseconds;
            }
            Array.Sort(times);report.AppendLine($"mode {mode}, contrast {strength}: {times[4]:F3} ms");
        }}finally{global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(t);global::WhimTex.Tests.UnityC.FixtureContext.Scope.Destroy(read);}
        return report.ToString();
    }

    public static string Capture() => global::WhimTex.Tests.TestContext.Result("skipped", 0, "Baseline-generation helper; never regenerate references to obtain a pass.").ToJson();

    public static string Compare() => FixtureReport(false);

    public static string Audit() => FixtureReport(true);

    public static string PairedPoisson() => global::WhimTex.Tests.UnityC.FixtureContext.RunReport("SeamlessOptimizationTests.PairedPoisson", ExecutePairedPoisson);

    static string FixtureReport(bool audit)
    {
        string label=audit?
            "SeamlessOptimizationTests.Audit: finiteness and caller-state assertions; delta report only, no equivalence tolerance":
            "SeamlessOptimizationTests.Compare";
        string report=null;
        string diagnostic=global::WhimTex.Tests.UnityC.ReviewedOracle.Seamless(label,snapshots=>{report=Fixtures(snapshots,audit);});
        // Auth/fixture/body failures and prerequisite SKIPs retain their exact result.
        if(report==null)return diagnostic;
        try
        {
            var json=Assembly.Load("Newtonsoft.Json");
            var objectType=json.GetType("Newtonsoft.Json.Linq.JObject",true);
            var valueType=json.GetType("Newtonsoft.Json.Linq.JValue",true);
            var item=objectType.GetProperty("Item",new[]{typeof(string)});
            object result=objectType.GetMethod("Parse",new[]{typeof(string)}).Invoke(null,new object[]{diagnostic});
            var status=item.GetValue(result,new object[]{"status"});
            if(status==null||status.ToString()!="passed")return diagnostic;
            var message=item.GetValue(result,new object[]{"message"});
            object text=valueType.GetConstructor(new[]{typeof(string)}).Invoke(new object[]{(message?.ToString()??label)+": "+report});
            item.SetValue(result,text,new object[]{"message"});
            return result.ToString(); // Append actual metrics only after assertions/owned cleanup passed.
        }
        catch(Exception error){return global::WhimTex.Tests.TestContext.Result("failed",0,label,error.ToString()).ToJson();}
    }

    public static string Benchmark() => global::WhimTex.Tests.UnityC.FixtureContext.Diagnostic("SeamlessOptimizationTests.Benchmark", ExecuteBenchmark);
}

namespace DCFApixels.WhimTex
{
    // Constant-screening gradient/data solve with discrete seam-slope constraints.
    // Projected, FFT-preconditioned CG; all reductions and channel steps stay on GPU.
    internal static class ScreenedOptimizationBaseline
    {
        internal static RenderTexture Render(Texture input, int width, int height)
            => RenderConfigured(input, width, height, MakeSeamlessLayerBehaviour.PoissonEdges.AllEdges, .05f);

        internal static RenderTexture RenderConfigured(Texture input, int width, int height,
            MakeSeamlessLayerBehaviour.PoissonEdges edges, float radius)
        {
            var m = Material("ScreenedSeamless");
            var fft = Material("GpuFourierTransform");
            if (m == null || fft == null || !m.shader.isSupported || !fft.shader.isSupported)
                throw new InvalidOperationException("Screened Poisson shader is unavailable.");
            var previous = RenderTexture.active;
            bool srgb = GL.sRGBWrite;
            var owned = new List<RenderTexture>();
            RenderTexture Temp(int w, int h)
            {
                var t = global::WhimTex.Tests.UnityC.FixtureContext.Scope.Temporary(RenderTexture.GetTemporary(w, h, 0, RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.Linear));
                t.filterMode = FilterMode.Point; t.wrapMode = TextureWrapMode.Clamp;
                owned.Add(t); return t;
            }
            try
            {
                GL.sRGBWrite = false;
                if (edges == MakeSeamlessLayerBehaviour.PoissonEdges.None)
                {
                    var copy=Temp(width,height); Graphics.Blit(input,copy);
                    copy.filterMode=FilterMode.Bilinear;
                    owned.Remove(copy); return copy;
                }
                bool wrapX = edges != MakeSeamlessLayerBehaviour.PoissonEdges.TopAndBottom;
                bool wrapY = edges != MakeSeamlessLayerBehaviour.PoissonEdges.LeftAndRight;
                int fw = wrapX ? width : width * 2, fh = wrapY ? height : height * 2;
                if (fw > SystemInfo.maxTextureSize || fh > SystemInfo.maxTextureSize)
                    throw new InvalidOperationException("Poisson direction requires a transform texture larger than this device supports.");
                var size = new Vector4(width, height, 1f / width, 1f / height);
                var fftSize = new Vector4(fw, fh, 1f / fw, 1f / fh);
                m.SetVector("_Size", size); fft.SetVector("_Size", fftSize);
                m.SetVector("_FftSize", fftSize);
                m.SetVector("_Axes", new Vector4(wrapX ? 1 : 0, wrapY ? 1 : 0, 0, 0));
                float length = radius * Mathf.Min(width, height);
                m.SetFloat("_Lambda", 1f / (length * length));
                var u = Temp(width,height); var x = Temp(width,height);
                var r = Temp(width,height); var p = Temp(width,height);
                var z = Temp(width,height); var ap = Temp(width,height);
                var scratch = Temp(width,height);
                var fa = Temp(fw,fh); var fb = Temp(fw,fh);
                var rz = Temp(1,1); var oldRz = Temp(1,1); var pap = Temp(1,1);
                var initialNorm = Temp(1,1); var norm = Temp(1,1);
                var reduction = new List<RenderTexture>();
                int rw = width, rh = height;
                do { rw = Mathf.Max(1,(rw+3)/4); rh = Mathf.Max(1,(rh+3)/4); reduction.Add(Temp(rw,rh)); }
                while (rw > 1 || rh > 1);

                void Project(RenderTexture source, RenderTexture destination)
                {
                    m.SetInt("_Axis",0); Graphics.Blit(source,scratch,m,1);
                    m.SetInt("_Axis",1); Graphics.Blit(scratch,destination,m,1);
                }
                void Apply(RenderTexture source, RenderTexture destination)
                {
                    Graphics.Blit(source,destination,m,2);
                    Project(destination,destination);
                }
                void Dot(RenderTexture a, RenderTexture b, RenderTexture destination)
                {
                    m.SetTexture("_Other",b);
                    Texture current = a;
                    for (int j=0;j<reduction.Count;j++)
                    {
                        m.SetVector("_ReduceSize",new Vector4(current.width,current.height,1f/current.width,1f/current.height));
                        m.SetInt("_Multiply",j==0?1:0);
                        Graphics.Blit(current,reduction[j],m,7); current=reduction[j];
                    }
                    Graphics.Blit(current,destination);
                }
                void Precondition()
                {
                    for (int pair=0;pair<2;pair++)
                    {
                        m.SetInt("_Pair",pair); Graphics.Blit(r,fa,m,4);
                        SeamlessFftBaseline.Transform(ref fa,ref fb,fft,fw,0,false);
                        SeamlessFftBaseline.Transform(ref fa,ref fb,fft,fh,1,false);
                        Graphics.Blit(fa,fb,m,5); Swap(ref fa,ref fb);
                        SeamlessFftBaseline.Transform(ref fa,ref fb,fft,fh,1,true);
                        SeamlessFftBaseline.Transform(ref fa,ref fb,fft,fw,0,true);
                        if (pair == 0) Graphics.Blit(fa,z,m,6);
                        else
                        {
                            m.SetTexture("_Other",z);
                            Graphics.Blit(fa,scratch,m,12); Graphics.Blit(scratch,z);
                        }
                    }
                    Project(z,z);
                }

                Graphics.Blit(input,u,m,0);
                Project(u,x);
                m.SetTexture("_Source",u); m.SetTexture("_X",x);
                // Solve for a correction to P*u. Sparse initial residual avoids
                // cancellation of lambda*u against large interior Laplacians.
                Graphics.Blit(u,r,m,3); Project(r,r);
                Dot(r,r,initialNorm); m.SetTexture("_InitialNorm",initialNorm);
                Precondition(); Graphics.Blit(z,p); Dot(r,z,rz);
                for (int iteration=0;iteration<16;iteration++)
                {
                    Dot(r,r,norm); m.SetTexture("_Norm",norm);
                    Apply(p,ap); Dot(p,ap,pap);
                    m.SetTexture("_RZ",rz); m.SetTexture("_PAP",pap);
                    m.SetTexture("_Direction",p); Graphics.Blit(x,scratch,m,8); Swap(ref x,ref scratch);
                    m.SetTexture("_Direction",ap); Graphics.Blit(r,scratch,m,9); Swap(ref r,ref scratch);
                    Precondition(); Swap(ref rz,ref oldRz); Dot(r,z,rz);
                    m.SetTexture("_RZ",rz); m.SetTexture("_OldRZ",oldRz);
                    m.SetTexture("_Z",z); Graphics.Blit(p,scratch,m,10); Swap(ref p,ref scratch);
                }
                Project(x,x);
                Graphics.Blit(x,scratch,m,11);
                scratch.filterMode = FilterMode.Bilinear;
                owned.Remove(scratch); return scratch;
            }
            finally
            {
                foreach (string property in new[]{"_Source","_X","_Other","_InitialNorm","_Norm","_RZ","_PAP","_Direction","_OldRZ","_Z"})
                    m.SetTexture(property,null);
                RenderTexture.active = previous; GL.sRGBWrite = srgb;
                foreach (var rt in owned) global::WhimTex.Tests.UnityC.FixtureContext.Scope.Release(rt);
            }
        }
        private static Material Material(string name)=>(Material)typeof(WhimTexDocument).Assembly.GetType("DCFApixels.WhimTex.WhimTexMaterials").GetProperty(name,System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic).GetValue(null);
        private static void Swap(ref RenderTexture a, ref RenderTexture b) { var t=a; a=b; b=t; }
    }
}
namespace DCFApixels.WhimTex
{
    internal static class SeamlessFftBaseline
    {
        internal static void Transform(ref RenderTexture a,ref RenderTexture b,Material material,int length,int axis,bool inverse)
        {
            if(length==1)return;
            var factors=new List<int>();int remaining=length;
            for(int divisor=2;divisor<=remaining/divisor;divisor++)
                while(remaining%divisor==0){factors.Add(divisor);remaining/=divisor;}
            if(remaining>1)factors.Add(remaining);factors.Reverse();
            var permutation=new Vector4[16];int stride=length;
            for(int i=0;i<factors.Count;i++){stride/=factors[i];permutation[i]=new Vector4(factors[i],stride,0,0);}
            material.SetInt("_Axis",axis);material.SetInt("_FactorCount",factors.Count);material.SetVectorArray("_Factors",permutation);
            Graphics.Blit(a,b,material,0);Swap(ref a,ref b);material.SetFloat("_Sign",inverse?1:-1);
            int previous=1;
            foreach(int radix in factors){material.SetInt("_Radix",radix);material.SetInt("_Previous",previous);material.SetFloat("_Scale",inverse?1f/radix:1);
                Graphics.Blit(a,b,material,1);Swap(ref a,ref b);previous*=radix;}
        }
        private static void Swap(ref RenderTexture a,ref RenderTexture b){var t=a;a=b;b=t;}
    }
}
