import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const core = read('src/TextureCompositor.cs');
const cache = read('src/TextureCompositor.EffectCache.cs');
const thumbs = read('src/TextureCompositor.Thumbnails.cs');
assert.match(core, /public Texture2D ComposeCanvas\(\)/);
assert.match(core, /internal Texture2D ComposeCanvas\(int maxSize\)/);
assert.match(core, /internal RenderTexture RenderCanvas\(int maxSize\)/);
assert.match(core, /internal RenderTexture RenderCanvasAtSize\(int outputWidth, int outputHeight\)\s*=>\s*RenderCanvasCore\(outputWidth, outputHeight, 1f\)/);
assert.match(core, /private Texture2D ComposeCanvasAtSize\(/);
assert.match(core, /private RenderTexture RenderCanvasCore\(/);
assert.match(core, /private void GetCanvasRenderSize\(/);
assert.match(cache, /internal RenderTexture RenderCanvasWithCache\(/);
assert.match(thumbs, /internal RenderTexture RenderLayerThumbnail\(/);
assert.match(core, /NormalizeModel\(\);\s*return ComposeCanvasAtSize\(width, height, 1f\)/);
assert.match(core, /maxSize = Mathf\.Max\(1, maxSize\)/);
assert.match(core, /float scale = Mathf\.Min\(1f, \(float\)maxSize \/ Mathf\.Max\(width, height\)\)/);
assert.match(core, /renderWidth = Mathf\.Max\(1, Mathf\.RoundToInt\(width \* scale\)\)/);
assert.match(core, /renderHeight = Mathf\.Max\(1, Mathf\.RoundToInt\(height \* scale\)\)/);
assert.match(core, /scaleMultiplier = Mathf\.Max\(\(float\)width \/ renderWidth, \(float\)height \/ renderHeight\)/);
assert.match(core, /HdrUtility\.ReadLinear\(composite\)/);
assert.match(core, /RenderTexture\.ReleaseTemporary\(composite\)/);
for (const source of [core, cache, thumbs])
  assert.doesNotMatch(source, /\b(?:Compose|ComposePreview|RenderPreview|RenderCachedPreview|GetPreviewDimensions|ComposeAtSize|RenderComposite|RenderAllLayers|RenderThumbnailLayer|previewWidth|previewHeight)\b/);
assert.match(core, /internal RenderTexture RenderLayerPreview\(/);
assert.match(core, /internal RenderTexture RenderAgentLayerPreview\(/);
assert.match(read('src/Editor/BrushPresetAssetEditor.cs'), /\bRenderPreview\(/);
assert.ok(read('src/ShaderFX.cs').includes('"_PreviewScale"'));
console.log('Canvas render naming: canonical signatures, scale math, ownership and intentional preview names passed.');
