import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = name => readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8');
const source = read('TextureCompositorWindow.FileNavigation.cs');
assert.match(read('TextureCompositorWindow.UI.cs'), /if \(TryOpenFileLayerDocument\(row, layer, evt\)\) return;/);
assert.match(source, /evt.button != 0 \|\| evt.clickCount != 2/);
assert.match(source, /evt.altKey \|\| evt.ctrlKey \|\| evt.commandKey \|\| evt.shiftKey/);
assert.match(source, /layer\?\.Behaviour is FileLayerBehaviour file/);
assert.match(source, /FindLayerDragControl\(row, evt.target as VisualElement\) != null/);
assert.match(source, /!IsLayerDragArea\(row, evt.target as VisualElement\)/);
assert.match(source, /TextureCompositor.FindDocument\(file.sourceTexture\)/);
assert.match(source, /activeLayerDrag\?\.Cancel\(\)/);
assert.match(source, /EditorApplication.delayCall/);
assert.match(source, /if \(this != null && document != null\)/);
assert.match(source, /candidate.compositor == document/);
assert.match(source, /existing.Show\(\);\s*existing.Focus\(\);\s*return existing;/);
assert.match(source, /CreateWindow<TextureCompositorWindow>\("WhimTex", typeof\(TextureCompositorWindow\)\)/);
assert.match(source, /window.SetCompositor\(document\)/);
assert.ok(!source.includes('GetWindow<'), 'Never replace a different window document');
assert.ok(!/SaveAssets|SaveWithOutput|ExecuteModelChange/.test(source), 'Navigation does not save or edit assets');
console.log('File layer document navigation routing and window reuse contracts passed.');
const newDocument = source.slice(source.indexOf('private TextureCompositorWindow OpenNewDocument()'), source.indexOf('private bool TryOpenFileLayerDocument'));
assert.match(read('TextureCompositorWindow.UI.cs'), /CreateToolbarButton\("New", \(\) => OpenNewDocument\(\), 46f\)/);
assert.match(newDocument, /CreateWindow<TextureCompositorWindow>/);
assert.match(newDocument, /FinishPaintingStroke\(\)/);
assert.match(newDocument, /window.RefreshDocumentTitle\(true\)/);
assert.ok(!/ResolveUnsavedTemporaryDocument|SetCompositor|GetWindow</.test(newDocument), 'New never replaces or resolves the current document');
