// WhimTex's own implementation of Ulichney's void-and-cluster construction.
// Algorithm reference: https://cv.ulichney.com/papers/1993-void-cluster.pdf
// Prints generated C# source as JSON; does not write files or run Unity.
import { pathToFileURL } from 'node:url';

export function ranks(width, height, seed) {
    const n = width * height, occupied = new Uint8Array(n), energy = new Float64Array(n);
    const kernel = [], radius = height === 1 ? 18 : 6, sigma = height === 1 ? 3 : 1.5;
    for (let dy = height === 1 ? 0 : -radius; dy <= (height === 1 ? 0 : radius); dy++)
        for (let dx = -radius; dx <= radius; dx++)
            kernel.push([dx, dy, Math.exp(-(dx * dx + dy * dy) / (2 * sigma * sigma))]);
    function update(index, present) {
        occupied[index] = present;
        const x = index % width, y = Math.floor(index / width), sign = present ? 1 : -1;
        for (const [dx, dy, weight] of kernel)
            energy[((y + dy + height) % height) * width + (x + dx + width) % width] += sign * weight;
    }
    function extreme(present) {
        let best = -1, score = present ? -Infinity : Infinity;
        for (let i = 0; i < n; i++) if (occupied[i] === present &&
            (present ? energy[i] > score : energy[i] < score)) { best = i; score = energy[i]; }
        return best;
    }
    function random() {
        seed ^= seed << 13; seed ^= seed >>> 17; seed ^= seed << 5;
        return (seed >>> 0) / 4294967296;
    }
    const order = Array.from({ length: n }, (_, i) => i);
    for (let i = n - 1; i > 0; i--) {
        const j = Math.floor(random() * (i + 1)); [order[i], order[j]] = [order[j], order[i]];
    }
    const initialCount = Math.floor(n * .1);
    for (let i = 0; i < initialCount; i++) update(order[i], 1);
    let converged = false;
    for (let step = 0; step < n * 10; step++) {
        const cluster = extreme(1); update(cluster, 0);
        const voidIndex = extreme(0); update(voidIndex, 1);
        if (cluster === voidIndex) { converged = true; break; }
    }
    if (!converged) throw new Error('Void-and-cluster relaxation did not converge');
    const initial = occupied.slice(), initialEnergy = energy.slice(), result = new Uint16Array(n);
    for (let rank = initialCount - 1; rank >= 0; rank--) {
        const index = extreme(1); update(index, 0); result[index] = rank;
    }
    occupied.set(initial); energy.set(initialEnergy);
    for (let rank = initialCount; rank < n / 2; rank++) {
        const index = extreme(0); update(index, 1); result[index] = rank;
    }
    const half = occupied.slice(); occupied.fill(0); energy.fill(0);
    for (let i = 0; i < n; i++) if (!half[i]) update(i, 1);
    for (let rank = n / 2; rank < n; rank++) {
        const index = extreme(1); update(index, 0); result[index] = rank;
    }
    return result;
}

export function rgba(width, height) {
    const n = width * height, data = Buffer.alloc(n * 4, 255);
    for (let channel = 0; channel < 3; channel++) {
        const values = ranks(width, height, [0x931af275, 0x327bc671, 0x6812aed7][channel]);
        for (let i = 0; i < n; i++) data[i * 4 + channel] = Math.floor(values[i] * 256 / n);
    }
    return data;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    function constant(name, data) {
        return `        internal const string ${name} =\n` + data.toString('base64').match(/.{1,120}/g)
            .map((s, i, a) => `            "${s}"${i === a.length - 1 ? ';' : ' +'}`).join('\n');
    }
    const source = '// Generated by Tests~/GenerateBlueNoise.mjs. WhimTex-generated data, not a third-party texture.\n'
        + 'namespace DCFApixels.SpriteEditor\n{\n    internal static class BlueNoiseData\n    {\n'
        + constant('TwoD', rgba(128, 128)) + '\n' + constant('OneD', rgba(256, 1)) + '\n    }\n}\n';
    process.stdout.write(JSON.stringify(source));
}
