import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = p => readFileSync(new URL('../src/' + p, import.meta.url), 'utf8');
const layer = read('Layers/GradientLayerBehaviour.cs');
const render = layer.slice(layer.indexOf('internal override RenderTexture Render'), layer.indexOf('private static void CopyGradient'));
assert.doesNotMatch(render, /GenerateGradientTexture|new Texture2D|\.Evaluate\(|ReadPixels|\.Apply\(/);
assert.match(render, /Graphics\.Blit\(null, source, material, 0\)/);
assert.match(render, /RenderTexture\.active = previous/);
assert.match(render, /GL\.sRGBWrite = srgb/);
assert.match(render, /RenderTexture\.ReleaseTemporary\(source\)/);
const palette = layer.slice(layer.indexOf('private void UpdatePalette'), layer.indexOf('public float GetGradientCoord'));
assert.ok(palette.indexOf('paletteGradient.EqualsRamp(evaluated)') < palette.indexOf('evaluated.ColorKeys'));
assert.match(palette, /palette\.GetRawTextureData<Color>\(\)/);
assert.match(palette, /WhimTexGradient paletteSource = evaluated\.Clone\(\)/);
assert.match(palette, /paletteSource\.WrapMode = WhimTexGradientWrapMode\.Clamp/);
assert.match(palette, /paletteSource\.Mode == WhimTexGradientMode\.Fixed/);
assert.match(render, /"_GradientWrapMode"/);
assert.match(layer, /destination = source\.Clone\(\)/);
assert.match(layer, /previewGradient\.Equals\(evaluated\)/);
assert.doesNotMatch(layer, /GradientUtility\.ComputeHash/);
assert.match(layer, /DestroyImmediate\(palette\)/);
const shader = read('Shaders/Gradient.shader');
assert.match(shader, /float4 _GradientIntervals\[129\]/);
assert.match(shader, /color\.rgb = SpriteDecode\(color\.rgb\)/);
assert.match(shader, /floor\(uv \* _GradientOutputSize\)/);
assert.match(shader, /all\(p == 0\)/);
assert.match(shader, /float WrapGradientTime\(float t\)/);
assert.match(shader, /frac\(t\)/);
assert.match(shader, /float mirrored = t - floor\(t \* \.5\) \* 2/);
assert.match(shader, /return mirrored <= 1 \? mirrored : 2 - mirrored/);
const key = Math.fround(.1);
const cancelled = Math.fround(1 - Math.abs(Math.fround(key - 1)));
assert.ok(cancelled > key, 'The old Mirror formula moved an exact Fixed boundary to the next interval');
const mirrored = Math.fround(key - Math.fround(Math.floor(Math.fround(key * .5)) * 2));
assert.equal(mirrored, key, 'Mirror must preserve interior coordinates exactly');
assert.match(read('Utils.cs'), /DestroyImmediate\(gradientMaterial\)/);
console.log('Gradient GPU: no full-size CPU generation, cached palette, native gradient snapshots, graphics-state and lifecycle contracts passed.');
const utils = read('Utils.cs');
assert.match(utils, /gradient\?\.Clone\(\)/);
assert.match(utils, /gradient\?\.GetHashCode\(\)/);
assert.match(read('Layers/Editors/GradientLayerEditorWindow.cs'), /layer\.gradient = GradientUtility\.Create\(evt\.newValue\)/);
console.log('Gradient settings copy preserves interpolation mode/color space and invalidates cached hashes.');
