import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = p => readFileSync(new URL('../src/' + p, import.meta.url), 'utf8');
const layer = read('Layers/GradientLayerBehaviour.cs');
const render = layer.slice(layer.indexOf('internal override RenderTexture Render'), layer.indexOf('private static void CopyGradient'));
assert.doesNotMatch(render, /GenerateGradientTexture|new Texture2D|\.Evaluate\(|ReadPixels|\.Apply\(/);
assert.match(render, /Graphics\.Blit\(null, source, material, 0\)/);
assert.match(render, /RenderTexture\.active = previous/);
assert.match(render, /GL\.sRGBWrite = srgb/);
assert.match(render, /RenderTexture\.ReleaseTemporary\(source\)/);
const palette = layer.slice(layer.indexOf('private void UpdatePalette'), layer.indexOf('public float GetGradientCoord'));
assert.ok(palette.indexOf('paletteGradient.Equals(evaluated)') < palette.indexOf('evaluated.ColorKeys'));
assert.match(palette, /palette\.GetRawTextureData<Color>\(\)/);
assert.match(palette, /evaluated\.Mode == WhimTexGradientMode\.Fixed/);
assert.match(layer, /destination = source\.Clone\(\)/);
assert.match(layer, /previewGradient\.Equals\(evaluated\)/);
assert.doesNotMatch(layer, /GradientUtility\.ComputeHash/);
assert.match(layer, /DestroyImmediate\(palette\)/);
const shader = read('Shaders/Gradient.shader');
assert.match(shader, /float4 _GradientIntervals\[129\]/);
assert.match(shader, /color\.rgb = SpriteDecode\(color\.rgb\)/);
assert.match(shader, /floor\(uv \* _GradientOutputSize\)/);
assert.match(shader, /all\(p == 0\)/);
assert.match(read('Utils.cs'), /DestroyImmediate\(gradientMaterial\)/);
console.log('Gradient GPU: no full-size CPU generation, cached palette, native gradient snapshots, graphics-state and lifecycle contracts passed.');
const utils = read('Utils.cs');
assert.match(utils, /gradient\?\.Clone\(\)/);
assert.match(utils, /gradient\?\.GetHashCode\(\)/);
assert.match(read('Layers/Editors/GradientLayerEditorWindow.cs'), /layer\.gradient = GradientUtility\.Create\(evt\.newValue\)/);
console.log('Gradient settings copy preserves interpolation mode/color space and invalidates cached hashes.');
