import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = name => readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8');
const renderer = read('TextureCompositor.LayerPicking.cs');
const window = read('TextureCompositorWindow.LayerPicking.cs');
const ui = read('TextureCompositorWindow.UI.cs');
const settings = read('WhimTexUserSettings.cs');
const settingsWindow = read('WhimTexUserSettingsWindow.cs');
const expression = renderer.match(/MeetsPickThreshold\(float alpha, float threshold\) => ([^;]+);/)[1];
const hit = new Function('alpha', 'threshold', `return ${expression.replace(/(\d)f\b/g, '$1')};`);
assert.equal(hit(0, 0), false);
assert.equal(hit(.0999756, .1), true);
assert.equal(hit(.099, .1), false);
assert.equal(hit(1, 1), true);
assert.equal(hit(NaN, .1), false);
assert.match(settings, /DefaultLayerPickAlphaThreshold = .1f/);
assert.match(settings, /EditorPrefs.SetFloat\(LayerPickAlphaKey, value\)/);
assert.match(settings, /LayerPickAlphaThreshold = DefaultLayerPickAlphaThreshold/);
for (const source of [window, settingsWindow]) {
    assert.match(source, /"Alpha ≥ %"/);
    assert.match(source, /LayerPickAlphaThreshold = evt.newValue \* .01f/);
    assert.match(source, /LayerPickAlphaThreshold \* 100f/);
}
assert.match(ui, /OnPreviewPointerDown\(PointerDownEvent evt\)\s*\{\s*previewPointerControl = evt.ctrlKey;\s*if \(HandleLayerPickPointerDown\(evt\)\)/);
assert.equal((ui.match(/HandleLayerPickPointerDown\(evt\)/g) ?? []).length, 1);
assert.match(window, /previewTool != PreviewTool.None/);
assert.match(window, /evt.button != 0 \|\| evt.altKey/);
assert.match(window, /evt.target != toolkitPreviewCanvas/);
assert.match(window, /evt.pressedButtons != 1/);
assert.match(window, /toolkitPreviewCanvas.ToCanvas\(evt.localPosition\)/);
assert.match(window, /if \(tiledPreview\) uv = new Vector2\(Mathf.Repeat/);
assert.match(window, /if \(evt.shiftKey\)/);
assert.match(window, /selectedLayerIds.Remove\(hit.Id\)/);
assert.match(window, /else SelectOnlyLayer\(hit\?\.Id\)/);
assert.match(window, /evt.ctrlKey \|\| evt.commandKey/);
assert.match(window, /!evt.shiftKey && selectedLayerIds.Count == 1 \? GetSelectedLayer\(\) : null/);
assert.match(renderer, /enteredGroups.Add\(selectedLayer\)/);
assert.match(renderer, /enteredGroups.Add\(parent\)/);
assert.match(renderer, /insideGroups \|\| enteredGroups\?\.Contains\(layer\) == true/);
assert.match(window, /groupExpansion\[parent.Id\] = true/);
assert.match(renderer, /sample.ReadPixels\(new Rect\(x, y, 1, 1\)/);
assert.match(renderer, /collectingErrors = previousErrors/);
assert.match(renderer, /effectCache = previousCache/);
assert.match(renderer, /FindClippingBaseIndex/);
assert.ok(!/MarkChanged\(|Undo\.|SetDirty\(/.test(renderer + window), 'Picking only changes window selection');
assert.match(read('TextureCompositorWindow.Transform.cs'), /previewSettingsTool = tool;/);
assert.match(read('TextureCompositorWindow.Tools.cs'), /Layer Select \(V\)/);
console.log('Layer picking threshold and UI integration contracts passed; GPU coverage uses LayerPickingSmoke.cs.');
