import fs from 'node:fs';
import assert from 'node:assert/strict';
const read = p => fs.readFileSync(new URL('../src/' + p, import.meta.url), 'utf8');
const topology = read('UvIslandMap.cs');
const uv = read('TextureCompositorWindow.Uv.cs');
const area = read('TextureCompositorWindow.AreaSelectionView.cs');
const tools = read('TextureCompositorWindow.Tools.cs');
const picker = read('TextureCompositorWindow.ShapePicker.cs');
assert.match(topology, /MeshUtility\.AcquireReadOnlyMeshData/);
assert.match(topology, /position\.Equals\(other\.position\) && uv\.Equals\(other\.uv\)/);
assert.match(topology, /edge\.count != 2/);
assert.match(topology, /Cross\(edge\.b - edge\.a, edge\.otherOpposite - edge\.a\) >= 0/);
assert.match(topology, /Check\(grid\[Cell\(uv\.y\)/);
assert.match(topology, /ValidateSize\(\)/);
assert.doesNotMatch(topology, /SetUVs|SetVertices|SetIndices|SaveAndReimport|Graphics\./);
assert.match(uv, /pickingMode = PickingMode\.Ignore/);
assert.match(uv, /s\.Set\(uvMap\.Rasterize\(island, s\.Width, s\.Height\), combine\)/);
assert.match(uv, /toolkitPreviewCanvas\.ToCanvas\(point\)/);
assert.match(uv, /toolkitPreviewCanvas\.ToView/);
assert.match(uv, /ReferenceEquals\(mesh, uvCachedMesh\)/);
assert.match(uv, /hash == uvCachedHash\) return;/);
assert.match(uv, /schedule\.Execute\(RefreshUvReference\)\.Every\(750\)/);
assert.match(uv, /\+\+batch == 512/);
const draw = uv.slice(uv.indexOf('private void DrawUvOverlay'));
assert.doesNotMatch(draw, /GetTriangles|AcquireReadOnlyMeshData|Rasterize|MarkDirtyRepaint|uvMap =[^=]/);
assert.match(area, /if \(owner\.IsUvSelectionTool\)[\s\S]*?owner\.SelectUvIsland[\s\S]*?return;/);
assert.match(uv, /previewTool == PreviewTool\.UvIslandSelect/);
assert.match(tools, /tool == PreviewTool\.UvIslandSelect/);
assert.match(read('TextureCompositorWindow.ContextTools.cs'), /"uvIslandSelectTool", PreviewTool\.UvIslandSelect/);
assert.doesNotMatch(picker, /"UV Island"/);
assert.match(read('TextureCompositor.cs'), /\[SerializeField, HideInInspector\] internal Mesh uvReferenceMesh/);
assert.match(read('TextureCompositorWindow.cs'), /private void OnDisable\(\)[\s\S]*?uvMap = null/);
console.log('UV overlay: read-only mesh, seam topology, cached geometry, bounded drawing batches, rotated picking, normal selection and lifecycle contracts passed.');
