import { TestContext, finish } from '../../Framework/test-api.mjs';
import { readFileSync } from 'node:fs';
const context = new TestContext('Shape corner contracts');
context.case('One contour and independent styles across UI, data and shader', () => {
  const assert = context.assert;
  const read = p => readFileSync(new URL('../../../src/' + p, import.meta.url), 'utf8');
  const geometry = read('Layers/ShapeContour.cs');
  const view = read('Layers/Editors/ShapeCornerSettingsView.cs');
  assert.match(geometry, /coefficients\[i\].*CornerStyle.Bevel[\s\S]*Mathf.Sqrt/);
  assert.match(geometry, /Vector2.Distance\(vertices\[i\], vertices\[j\]\) \/ consumed/);
  assert.match(geometry, /value.style == values\[index\].style/);
  assert.match(geometry, /values\[neighbour\].amount = Mathf.Min/);
  assert.match(geometry, /RoundArc\(entry\[i\], exit\[i\]/);
  assert.match(view, /"Top Left", "Top Right", "Bottom Right", "Bottom Left"/);
  assert.match(view, /"Outer" : "Inner"/);
  assert.match(view, /new EnumField\(Get\(index\).style\)/);
  assert.match(view, /new FloatField\(label\)/);
  assert.match(view, /class CornerStyleIcon : VisualElement/);
  assert.match(view, /value == CornerStyle.Round.*BezierCurveTo/);
  assert.match(view, /contour.CopyPreview\(shape, size, points\)/);
  assert.match(view, /polygon && count > 8/);
  assert.doesNotMatch(view, /\.style\./);
  const uss = read('WhimTexSplitView.uss');
  assert.match(uss, /\.whimtex-shape-corner-style .unity-enum-field__text \{ display: none; \}/);
  assert.match(uss, /\.whimtex-shape-corner-nw \{ left: 0; top: 0; \}/);
  assert.match(view, /layer.SetCorner\(index, value, layer.GeometryHalfSize\(document\)\)/);
  assert.match(view, /cornerBindings.Track\(amount, \(\) => Get\(index\).amount \* 100f\)/);
  assert.match(view, /cornerBindings.Clear\(\)/);
  assert.match(read('WhimTexDocument.cs'), /RefreshTransformHierarchy\(\);\s*NormalizeShapeCorners\(layers\)/);
  assert.match(read('Shaders/Shape.shader'), /ArcCrossing/);
  assert.match(read('Shaders/Shape.shader'), /distance \* \(inside \? -1 : 1\)/);
  assert.doesNotMatch(read('Layers/ShapeLayerBehaviour.cs'), /cornerRoundness|GetCornerRoundness|AdjustCorner|FormerlySerializedAs/);
});
await finish(context);
