// Generated by Tests~/GenerateDocumentSerialization.cs from the serializer's own field table.
// Do not edit by hand: regenerate when fields change. Values keep the automatic encoding, so a
// document stays readable whichever pass wrote it.

namespace DCFApixels.WhimTex
{
    public partial class LayerBehaviour : IWhimTexDocumentSerializable
    {
        public void WriteDocument(IWhimTexDocumentWriter writer)
        {
            if (!CoversAllFields()) { writer.WriteAutomaticFields(this); return; }
            writer.Begin(CountLevels());
            WriteLevels(writer);
        }

        public void ReadDocument(IWhimTexDocumentReader reader)
        {
            if (!CoversAllFields()) { reader.ReadAutomaticFields(this); return; }
            int count = reader.Count;
            for (int i = 0; i < count; i++)
            {
                string name = reader.NextName();
                if (!ReadOwn(name, reader)) reader.Skip();
            }
        }

        private static readonly System.Collections.Generic.Dictionary<System.Type, bool> Coverage = new System.Collections.Generic.Dictionary<System.Type, bool>();

        /// <summary>
        /// Generated code is used only while it covers exactly the fields the automatic pass would
        /// write. A behaviour defined outside this assembly, or a field added since the last
        /// generation, falls back to the automatic pass instead of losing its values.
        /// </summary>
        private bool CoversAllFields()
        {
            System.Type type = GetType();
            lock (Coverage)
            {
                if (Coverage.TryGetValue(type, out bool cached)) return cached;
            }
            bool covers = CountLevels() == WhimTexDocumentSerializer.ReflectedFieldCount(type);
            lock (Coverage) Coverage[type] = covers;
            return covers;
        }

        protected virtual int CountLevels() => 1;

        protected virtual void WriteLevels(IWhimTexDocumentWriter writer)
        {
            writer.Write("recoveryId", recoveryId);
        }

        protected virtual bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "recoveryId": recoveryId = reader.ReadString(); return true;
            }
            return false;
        }
    }

    public partial class TargetedLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 2;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.Write("targetLayerId", targetLayerId);
            writer.WriteEnum("inputMode", inputMode);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "targetLayerId": targetLayerId = reader.ReadString(); return true;
                case "inputMode": inputMode = reader.ReadEnum<DCFApixels.WhimTex.EffectInputMode>(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class BlurLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 9;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.Write("strength", strength);
            writer.Write("radius", radius);
            writer.Write("distance", distance);
            writer.Write("angle", angle);
            writer.Write("arc", arc);
            writer.Write("center", center);
            writer.WriteEnum("direction", direction);
            writer.WriteEnum("edges", edges);
            writer.WriteEnum("mode", mode);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "strength": strength = reader.ReadFloat(); return true;
                case "radius": radius = reader.ReadFloat(); return true;
                case "distance": distance = reader.ReadFloat(); return true;
                case "angle": angle = reader.ReadFloat(); return true;
                case "arc": arc = reader.ReadFloat(); return true;
                case "center": center = reader.ReadVector2(); return true;
                case "direction": direction = reader.ReadEnum<DCFApixels.WhimTex.BlurLayerBehaviour.MotionDirection>(); return true;
                case "edges": edges = reader.ReadEnum<DCFApixels.WhimTex.BlurLayerBehaviour.EdgeMode>(); return true;
                case "mode": mode = reader.ReadEnum<DCFApixels.WhimTex.BlurType>(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class ColorFillLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 2;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("mode", mode);
            writer.Write("storedColor", storedColor);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "mode": mode = reader.ReadEnum<DCFApixels.WhimTex.ColorFillLayerBehaviour.FillMode>(); return true;
                case "storedColor": storedColor = reader.ReadColor(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class DrawingLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 26;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteTexture("pixels", pixels);
            writer.Write("pixelsRevision", pixelsRevision);
            writer.Write("originalImageUrl", originalImageUrl);
            writer.Write("originalImageRevision", originalImageRevision);
            writer.WriteEnum("tool", tool);
            writer.Write("brushColor", brushColor);
            writer.Write("secondaryBrushColor", secondaryBrushColor);
            writer.Write("brushSize", brushSize);
            writer.Write("brushHardness", brushHardness);
            writer.Write("brushSpacing", brushSpacing);
            writer.WriteObject("brushDynamics", brushDynamics, typeof(DCFApixels.WhimTex.BrushDynamics));
            writer.WriteEnum("fillSampleMode", fillSampleMode);
            writer.Write("fillContiguous", fillContiguous);
            writer.Write("fillTolerance", fillTolerance);
            writer.Write("fillAntialias", fillAntialias);
            writer.Write("fillExpand", fillExpand);
            writer.Write("mirrorAcrossVerticalAxis", mirrorAcrossVerticalAxis);
            writer.Write("mirrorAcrossHorizontalAxis", mirrorAcrossHorizontalAxis);
            writer.Write("mirrorAngle", mirrorAngle);
            writer.Write("patternCenter", patternCenter);
            writer.WriteEnum("repeatMode", repeatMode);
            writer.WriteEnum("repeatElementMode", repeatElementMode);
            writer.WriteEnum("repeatBoundaryMode", repeatBoundaryMode);
            writer.Write("repeatCount", repeatCount);
            writer.Write("repeatSecondaryCount", repeatSecondaryCount);
            writer.Write("radialStartAngle", radialStartAngle);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "pixels": pixels = reader.ReadTexture(); return true;
                case "pixelsRevision": pixelsRevision = reader.ReadInt(); return true;
                case "originalImageUrl": originalImageUrl = reader.ReadString(); return true;
                case "originalImageRevision": originalImageRevision = reader.ReadInt(); return true;
                case "tool": tool = reader.ReadEnum<DCFApixels.WhimTex.PaintToolMode>(); return true;
                case "brushColor": brushColor = reader.ReadColor(); return true;
                case "secondaryBrushColor": secondaryBrushColor = reader.ReadColor(); return true;
                case "brushSize": brushSize = reader.ReadFloat(); return true;
                case "brushHardness": brushHardness = reader.ReadFloat(); return true;
                case "brushSpacing": brushSpacing = reader.ReadFloat(); return true;
                case "brushDynamics": brushDynamics = (DCFApixels.WhimTex.BrushDynamics)reader.ReadObject(typeof(DCFApixels.WhimTex.BrushDynamics)); return true;
                case "fillSampleMode": fillSampleMode = reader.ReadEnum<DCFApixels.WhimTex.FillSampleMode>(); return true;
                case "fillContiguous": fillContiguous = reader.ReadBool(); return true;
                case "fillTolerance": fillTolerance = reader.ReadInt(); return true;
                case "fillAntialias": fillAntialias = reader.ReadBool(); return true;
                case "fillExpand": fillExpand = reader.ReadInt(); return true;
                case "mirrorAcrossVerticalAxis": mirrorAcrossVerticalAxis = reader.ReadBool(); return true;
                case "mirrorAcrossHorizontalAxis": mirrorAcrossHorizontalAxis = reader.ReadBool(); return true;
                case "mirrorAngle": mirrorAngle = reader.ReadFloat(); return true;
                case "patternCenter": patternCenter = reader.ReadVector2(); return true;
                case "repeatMode": repeatMode = reader.ReadEnum<DCFApixels.WhimTex.PaintRepeatMode>(); return true;
                case "repeatElementMode": repeatElementMode = reader.ReadEnum<DCFApixels.WhimTex.PaintRepeatElementMode>(); return true;
                case "repeatBoundaryMode": repeatBoundaryMode = reader.ReadEnum<DCFApixels.WhimTex.PaintRepeatBoundaryMode>(); return true;
                case "repeatCount": repeatCount = reader.ReadInt(); return true;
                case "repeatSecondaryCount": repeatSecondaryCount = reader.ReadInt(); return true;
                case "radialStartAngle": radialStartAngle = reader.ReadFloat(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class FileLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 4;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteTexture("sourceTexture", sourceTexture);
            writer.Write("sourceAssigned", sourceAssigned);
            writer.Write("portableAssetGuid", portableAssetGuid);
            writer.Write("portableAssetLocalId", portableAssetLocalId);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "sourceTexture": sourceTexture = reader.ReadTexture(); return true;
                case "sourceAssigned": sourceAssigned = reader.ReadBool(); return true;
                case "portableAssetGuid": portableAssetGuid = reader.ReadString(); return true;
                case "portableAssetLocalId": portableAssetLocalId = reader.ReadString(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class GradientLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 4;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("gradientType", gradientType);
            writer.WriteObject("gradient", gradient, typeof(DCFApixels.WhimTex.WhimTexGradient));
            writer.Write("circularRepetitions", circularRepetitions);
            writer.WriteEnum("circularWrapMode", circularWrapMode);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "gradientType": gradientType = reader.ReadEnum<DCFApixels.WhimTex.GradientLayerBehaviour.GradientType>(); return true;
                case "gradient": gradient = (DCFApixels.WhimTex.WhimTexGradient)reader.ReadObject(typeof(DCFApixels.WhimTex.WhimTexGradient)); return true;
                case "circularRepetitions": circularRepetitions = reader.ReadFloat(); return true;
                case "circularWrapMode": circularWrapMode = reader.ReadEnum<DCFApixels.WhimTex.GradientLayerBehaviour.WrapMode>(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class GroupLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 0;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class MakeSeamlessLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 4;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("horizontal", horizontal);
            writer.WriteEnum("vertical", vertical);
            writer.Write("blendWidth", blendWidth);
            writer.Write("falloff", falloff);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "horizontal": horizontal = reader.ReadEnum<DCFApixels.WhimTex.MakeSeamlessLayerBehaviour.HorizontalDirection>(); return true;
                case "vertical": vertical = reader.ReadEnum<DCFApixels.WhimTex.MakeSeamlessLayerBehaviour.VerticalDirection>(); return true;
                case "blendWidth": blendWidth = reader.ReadFloat(); return true;
                case "falloff": falloff = reader.ReadFloat(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class NoiseLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 21;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("noiseType", noiseType);
            writer.WriteEnum("whiteNoiseColor", whiteNoiseColor);
            writer.Write("whiteNoiseSize", whiteNoiseSize);
            writer.WriteEnum("dimensions", dimensions);
            writer.Write("direction", direction);
            writer.Write("seed", seed);
            writer.Write("scale", scale);
            writer.Write("offset", offset);
            writer.WriteEnum("fractal", fractal);
            writer.Write("octaves", octaves);
            writer.Write("lacunarity", lacunarity);
            writer.Write("gain", gain);
            writer.Write("weightedStrength", weightedStrength);
            writer.Write("pingPongStrength", pingPongStrength);
            writer.WriteEnum("cellularDistance", cellularDistance);
            writer.WriteEnum("cellularReturn", cellularReturn);
            writer.Write("cellularJitter", cellularJitter);
            writer.WriteEnum("warp", warp);
            writer.Write("warpStrength", warpStrength);
            writer.WriteEnum("encoding", encoding);
            writer.Write("inverted", inverted);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "noiseType": noiseType = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.NoiseType>(); return true;
                case "whiteNoiseColor": whiteNoiseColor = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.WhiteNoiseColor>(); return true;
                case "whiteNoiseSize": whiteNoiseSize = reader.ReadFloat(); return true;
                case "dimensions": dimensions = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.NoiseDimensions>(); return true;
                case "direction": direction = reader.ReadFloat(); return true;
                case "seed": seed = reader.ReadInt(); return true;
                case "scale": scale = reader.ReadFloat(); return true;
                case "offset": offset = reader.ReadVector2(); return true;
                case "fractal": fractal = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.FractalType>(); return true;
                case "octaves": octaves = reader.ReadInt(); return true;
                case "lacunarity": lacunarity = reader.ReadFloat(); return true;
                case "gain": gain = reader.ReadFloat(); return true;
                case "weightedStrength": weightedStrength = reader.ReadFloat(); return true;
                case "pingPongStrength": pingPongStrength = reader.ReadFloat(); return true;
                case "cellularDistance": cellularDistance = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.CellularDistance>(); return true;
                case "cellularReturn": cellularReturn = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.CellularReturn>(); return true;
                case "cellularJitter": cellularJitter = reader.ReadFloat(); return true;
                case "warp": warp = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.WarpType>(); return true;
                case "warpStrength": warpStrength = reader.ReadFloat(); return true;
                case "encoding": encoding = reader.ReadEnum<DCFApixels.WhimTex.NoiseLayerBehaviour.OutputEncoding>(); return true;
                case "inverted": inverted = reader.ReadBool(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class NormalMapLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 23;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("mode", mode);
            writer.WriteEnum("sourceChannel", sourceChannel);
            writer.WriteEnum("inputSpace", inputSpace);
            writer.WriteEnum("edges", edges);
            writer.WriteEnum("derivative", derivative);
            writer.WriteEnum("alphaMode", alphaMode);
            writer.WriteEnum("output", output);
            writer.WriteEnum("encoding", encoding);
            writer.Write("strength", strength);
            writer.Write("blackLevel", blackLevel);
            writer.Write("whiteLevel", whiteLevel);
            writer.Write("gamma", gamma);
            writer.Write("smoothing", smoothing);
            writer.Write("mediumRadius", mediumRadius);
            writer.Write("largeRadius", largeRadius);
            writer.Write("fineDetail", fineDetail);
            writer.Write("mediumDetail", mediumDetail);
            writer.Write("largeDetail", largeDetail);
            writer.Write("lightRemoval", lightRemoval);
            writer.Write("inverted", inverted);
            writer.Write("flipX", flipX);
            writer.Write("flipY", flipY);
            writer.Write("ignoreTransparent", ignoreTransparent);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "mode": mode = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.GenerationMode>(); return true;
                case "sourceChannel": sourceChannel = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.HeightChannel>(); return true;
                case "inputSpace": inputSpace = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.InputSpace>(); return true;
                case "edges": edges = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.EdgeMode>(); return true;
                case "derivative": derivative = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.DerivativeFilter>(); return true;
                case "alphaMode": alphaMode = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.AlphaMode>(); return true;
                case "output": output = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.OutputMode>(); return true;
                case "encoding": encoding = reader.ReadEnum<DCFApixels.WhimTex.NormalMapLayerBehaviour.OutputEncoding>(); return true;
                case "strength": strength = reader.ReadFloat(); return true;
                case "blackLevel": blackLevel = reader.ReadFloat(); return true;
                case "whiteLevel": whiteLevel = reader.ReadFloat(); return true;
                case "gamma": gamma = reader.ReadFloat(); return true;
                case "smoothing": smoothing = reader.ReadFloat(); return true;
                case "mediumRadius": mediumRadius = reader.ReadFloat(); return true;
                case "largeRadius": largeRadius = reader.ReadFloat(); return true;
                case "fineDetail": fineDetail = reader.ReadFloat(); return true;
                case "mediumDetail": mediumDetail = reader.ReadFloat(); return true;
                case "largeDetail": largeDetail = reader.ReadFloat(); return true;
                case "lightRemoval": lightRemoval = reader.ReadFloat(); return true;
                case "inverted": inverted = reader.ReadBool(); return true;
                case "flipX": flipX = reader.ReadBool(); return true;
                case "flipY": flipY = reader.ReadBool(); return true;
                case "ignoreTransparent": ignoreTransparent = reader.ReadBool(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class OutlineLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 8;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("metric", metric);
            writer.Write("outlineColor", outlineColor);
            writer.Write("outlineWidth", outlineWidth);
            writer.Write("outlineSoftness", outlineSoftness);
            writer.Write("outlineOffset", outlineOffset);
            writer.Write("fillCenter", fillCenter);
            writer.Write("fillColor", fillColor);
            writer.WriteEnum("outlinePosition", outlinePosition);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "metric": metric = reader.ReadEnum<DCFApixels.WhimTex.DistanceMetric>(); return true;
                case "outlineColor": outlineColor = reader.ReadColor(); return true;
                case "outlineWidth": outlineWidth = reader.ReadFloat(); return true;
                case "outlineSoftness": outlineSoftness = reader.ReadFloat(); return true;
                case "outlineOffset": outlineOffset = reader.ReadFloat(); return true;
                case "fillCenter": fillCenter = reader.ReadBool(); return true;
                case "fillColor": fillColor = reader.ReadColor(); return true;
                case "outlinePosition": outlinePosition = reader.ReadEnum<DCFApixels.WhimTex.OutlineLayerBehaviour.OutlinePosition>(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class PendingLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 1;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.Write("jobId", jobId);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "jobId": jobId = reader.ReadString(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class SDFLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 13;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("metric", metric);
            writer.WriteEnum("sourceChannel", sourceChannel);
            writer.WriteObject("threshold", threshold, typeof(System.Byte));
            writer.WriteEnum("distancePosition", distancePosition);
            writer.Write("inverted", inverted);
            writer.Write("maxDistanceNormalization", maxDistanceNormalization);
            writer.Write("sourceOffset", sourceOffset);
            writer.WriteEnum("sourceEdges", sourceEdges);
            writer.Write("contourOffset", contourOffset);
            writer.Write("insideDistance", insideDistance);
            writer.Write("outsideDistance", outsideDistance);
            writer.Write("profile", profile);
            writer.WriteObject("gradient", gradient, typeof(DCFApixels.WhimTex.WhimTexGradient));
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "metric": metric = reader.ReadEnum<DCFApixels.WhimTex.DistanceMetric>(); return true;
                case "sourceChannel": sourceChannel = reader.ReadEnum<DCFApixels.WhimTex.SDFLayerBehaviour.SourceChannel>(); return true;
                case "threshold": threshold = (System.Byte)reader.ReadObject(typeof(System.Byte)); return true;
                case "distancePosition": distancePosition = reader.ReadEnum<DCFApixels.WhimTex.SDFLayerBehaviour.DistancePosition>(); return true;
                case "inverted": inverted = reader.ReadBool(); return true;
                case "maxDistanceNormalization": maxDistanceNormalization = reader.ReadFloat(); return true;
                case "sourceOffset": sourceOffset = reader.ReadVector2(); return true;
                case "sourceEdges": sourceEdges = reader.ReadEnum<DCFApixels.WhimTex.SDFLayerBehaviour.SourceEdges>(); return true;
                case "contourOffset": contourOffset = reader.ReadFloat(); return true;
                case "insideDistance": insideDistance = reader.ReadFloat(); return true;
                case "outsideDistance": outsideDistance = reader.ReadFloat(); return true;
                case "profile": profile = reader.ReadCurve(); return true;
                case "gradient": gradient = (DCFApixels.WhimTex.WhimTexGradient)reader.ReadObject(typeof(DCFApixels.WhimTex.WhimTexGradient)); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class ShaderProcessorLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 0;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class ShapeLayerBehaviour
    {
        protected override int CountLevels() => base.CountLevels() + 11;

        protected override void WriteLevels(IWhimTexDocumentWriter writer)
        {
            base.WriteLevels(writer);
            writer.WriteEnum("kind", kind);
            writer.Write("fillColor", fillColor);
            writer.Write("fill", fill);
            writer.Write("stroke", stroke);
            writer.Write("strokeColor", strokeColor);
            writer.Write("strokeWidth", strokeWidth);
            writer.Write("roundness", roundness);
            writer.Write("cornerRoundness", cornerRoundness);
            writer.Write("linkCorners", linkCorners);
            writer.Write("sides", sides);
            writer.Write("innerRadius", innerRadius);
        }

        protected override bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "kind": kind = reader.ReadEnum<DCFApixels.WhimTex.ShapeLayerBehaviour.ShapeKind>(); return true;
                case "fillColor": fillColor = reader.ReadColor(); return true;
                case "fill": fill = reader.ReadBool(); return true;
                case "stroke": stroke = reader.ReadBool(); return true;
                case "strokeColor": strokeColor = reader.ReadColor(); return true;
                case "strokeWidth": strokeWidth = reader.ReadFloat(); return true;
                case "roundness": roundness = reader.ReadFloat(); return true;
                case "cornerRoundness": cornerRoundness = reader.ReadVector4(); return true;
                case "linkCorners": linkCorners = reader.ReadBool(); return true;
                case "sides": sides = reader.ReadInt(); return true;
                case "innerRadius": innerRadius = reader.ReadFloat(); return true;
            }
            return base.ReadOwn(name, reader);
        }
    }

    public partial class Layer : IWhimTexDocumentSerializable
    {
        public void WriteDocument(IWhimTexDocumentWriter writer)
        {
            if (!CoversAllFields()) { writer.WriteAutomaticFields(this); return; }
            writer.Begin(CountLevels());
            WriteLevels(writer);
        }

        public void ReadDocument(IWhimTexDocumentReader reader)
        {
            if (!CoversAllFields()) { reader.ReadAutomaticFields(this); return; }
            int count = reader.Count;
            for (int i = 0; i < count; i++)
            {
                string name = reader.NextName();
                if (!ReadOwn(name, reader)) reader.Skip();
            }
        }

        private static readonly System.Collections.Generic.Dictionary<System.Type, bool> Coverage = new System.Collections.Generic.Dictionary<System.Type, bool>();

        /// <summary>
        /// Generated code is used only while it covers exactly the fields the automatic pass would
        /// write. A behaviour defined outside this assembly, or a field added since the last
        /// generation, falls back to the automatic pass instead of losing its values.
        /// </summary>
        private bool CoversAllFields()
        {
            System.Type type = GetType();
            lock (Coverage)
            {
                if (Coverage.TryGetValue(type, out bool cached)) return cached;
            }
            bool covers = CountLevels() == WhimTexDocumentSerializer.ReflectedFieldCount(type);
            lock (Coverage) Coverage[type] = covers;
            return covers;
        }

        protected int CountLevels() => 17;

        protected void WriteLevels(IWhimTexDocumentWriter writer)
        {
            writer.Write("id", id);
            writer.Write("layerName", layerName);
            writer.Write("enabled", enabled);
            writer.Write("clippingMask", clippingMask);
            writer.Write("opacity", opacity);
            writer.WriteEnum("blendMode", blendMode);
            writer.WriteEnum("colorRange", colorRange);
            writer.WriteEnum("blendRange", blendRange);
            writer.WriteObject("swizzle", swizzle, typeof(DCFApixels.WhimTex.LayerSwizzle));
            writer.WriteList("modifiers", modifiers, typeof(System.Collections.Generic.List<UnityEngine.Object>));
            writer.WriteObject("transform", transform, typeof(DCFApixels.WhimTex.TextureTransform));
            writer.WriteEnum("filterMode", filterMode);
            writer.WriteObject("behaviour", behaviour, typeof(DCFApixels.WhimTex.LayerBehaviour));
            writer.Write("behaviourId", behaviourId);
            writer.WriteList("children", children, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.Layer>));
            writer.Write("group", group);
            writer.WriteEnum("compositing", compositing);
        }

        protected bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "id": id = reader.ReadString(); return true;
                case "layerName": layerName = reader.ReadString(); return true;
                case "enabled": enabled = reader.ReadBool(); return true;
                case "clippingMask": clippingMask = reader.ReadBool(); return true;
                case "opacity": opacity = reader.ReadFloat(); return true;
                case "blendMode": blendMode = reader.ReadEnum<DCFApixels.WhimTex.BlendMode>(); return true;
                case "colorRange": colorRange = reader.ReadEnum<DCFApixels.WhimTex.LayerColorRange>(); return true;
                case "blendRange": blendRange = reader.ReadEnum<DCFApixels.WhimTex.LayerBlendRange>(); return true;
                case "swizzle": swizzle = (DCFApixels.WhimTex.LayerSwizzle)reader.ReadObject(typeof(DCFApixels.WhimTex.LayerSwizzle)); return true;
                case "modifiers": modifiers = (System.Collections.Generic.List<UnityEngine.Object>)reader.ReadList(typeof(System.Collections.Generic.List<UnityEngine.Object>)); return true;
                case "transform": transform = (DCFApixels.WhimTex.TextureTransform)reader.ReadObject(typeof(DCFApixels.WhimTex.TextureTransform)); return true;
                case "filterMode": filterMode = reader.ReadEnum<DCFApixels.WhimTex.LayerFilterMode>(); return true;
                case "behaviour": behaviour = (DCFApixels.WhimTex.LayerBehaviour)reader.ReadObject(typeof(DCFApixels.WhimTex.LayerBehaviour)); return true;
                case "behaviourId": behaviourId = reader.ReadString(); return true;
                case "children": children = (System.Collections.Generic.List<DCFApixels.WhimTex.Layer>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.Layer>)); return true;
                case "group": group = reader.ReadBool(); return true;
                case "compositing": compositing = reader.ReadEnum<DCFApixels.WhimTex.GroupCompositing>(); return true;
            }
            return false;
        }
    }

    public partial class ShaderFX : IWhimTexDocumentSerializable
    {
        public void WriteDocument(IWhimTexDocumentWriter writer)
        {
            if (!CoversAllFields()) { writer.WriteAutomaticFields(this); return; }
            writer.Begin(CountLevels());
            WriteLevels(writer);
        }

        public void ReadDocument(IWhimTexDocumentReader reader)
        {
            if (!CoversAllFields()) { reader.ReadAutomaticFields(this); return; }
            int count = reader.Count;
            for (int i = 0; i < count; i++)
            {
                string name = reader.NextName();
                if (!ReadOwn(name, reader)) reader.Skip();
            }
        }

        private static readonly System.Collections.Generic.Dictionary<System.Type, bool> Coverage = new System.Collections.Generic.Dictionary<System.Type, bool>();

        /// <summary>
        /// Generated code is used only while it covers exactly the fields the automatic pass would
        /// write. A behaviour defined outside this assembly, or a field added since the last
        /// generation, falls back to the automatic pass instead of losing its values.
        /// </summary>
        private bool CoversAllFields()
        {
            System.Type type = GetType();
            lock (Coverage)
            {
                if (Coverage.TryGetValue(type, out bool cached)) return cached;
            }
            bool covers = CountLevels() == WhimTexDocumentSerializer.ReflectedFieldCount(type);
            lock (Coverage) Coverage[type] = covers;
            return covers;
        }

        protected int CountLevels() => 7;

        protected void WriteLevels(IWhimTexDocumentWriter writer)
        {
            writer.Write("catalogGuid", catalogGuid);
            writer.Write("catalogSourcePath", catalogSourcePath);
            writer.Write("catalogDependencyHash", catalogDependencyHash);
            writer.Write("active", active);
            writer.Write("code", code);
            writer.WriteList("parameters", parameters, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFXParameter>));
            writer.Write("shaderKey", shaderKey);
        }

        protected bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "catalogGuid": catalogGuid = reader.ReadString(); return true;
                case "catalogSourcePath": catalogSourcePath = reader.ReadString(); return true;
                case "catalogDependencyHash": catalogDependencyHash = reader.ReadString(); return true;
                case "active": active = reader.ReadBool(); return true;
                case "code": code = reader.ReadString(); return true;
                case "parameters": parameters = (System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFXParameter>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFXParameter>)); return true;
                case "shaderKey": shaderKey = reader.ReadString(); return true;
            }
            return false;
        }
    }

    public partial class TextureCompositor : IWhimTexDocumentSerializable
    {
        public void WriteDocument(IWhimTexDocumentWriter writer)
        {
            if (!CoversAllFields()) { writer.WriteAutomaticFields(this); return; }
            writer.Begin(CountLevels());
            WriteLevels(writer);
        }

        public void ReadDocument(IWhimTexDocumentReader reader)
        {
            if (!CoversAllFields()) { reader.ReadAutomaticFields(this); return; }
            int count = reader.Count;
            for (int i = 0; i < count; i++)
            {
                string name = reader.NextName();
                if (!ReadOwn(name, reader)) reader.Skip();
            }
        }

        private static readonly System.Collections.Generic.Dictionary<System.Type, bool> Coverage = new System.Collections.Generic.Dictionary<System.Type, bool>();

        /// <summary>
        /// Generated code is used only while it covers exactly the fields the automatic pass would
        /// write. A behaviour defined outside this assembly, or a field added since the last
        /// generation, falls back to the automatic pass instead of losing its values.
        /// </summary>
        private bool CoversAllFields()
        {
            System.Type type = GetType();
            lock (Coverage)
            {
                if (Coverage.TryGetValue(type, out bool cached)) return cached;
            }
            bool covers = CountLevels() == WhimTexDocumentSerializer.ReflectedFieldCount(type);
            lock (Coverage) Coverage[type] = covers;
            return covers;
        }

        protected int CountLevels() => 13;

        protected void WriteLevels(IWhimTexDocumentWriter writer)
        {
            writer.WriteObject("outputSettings", outputSettings, typeof(DCFApixels.WhimTex.TextureCompositor.OutputSettings));
            writer.WriteList("layerNameCounters", layerNameCounters, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.LayerNameCounter>));
            writer.Write("nextCopyNumber", nextCopyNumber);
            writer.Write("savedOutputSettings", savedOutputSettings);
            writer.WriteList("spriteSlices", spriteSlices, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.SpriteSlice>));
            writer.Write("width", width);
            writer.Write("height", height);
            writer.WriteEnum("outputFilter", outputFilter);
            writer.WriteReference("uvReferenceMesh", uvReferenceMesh);
            writer.Write("uvReferenceChannel", uvReferenceChannel);
            writer.Write("uvReferenceSubmesh", uvReferenceSubmesh);
            writer.WriteList("layers", layers, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.Layer>));
            writer.WriteList("embeddedShaderFX", embeddedShaderFX, typeof(System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFX>));
        }

        protected bool ReadOwn(string name, IWhimTexDocumentReader reader)
        {
            switch (name)
            {
                case "outputSettings": outputSettings = (DCFApixels.WhimTex.TextureCompositor.OutputSettings)reader.ReadObject(typeof(DCFApixels.WhimTex.TextureCompositor.OutputSettings)); return true;
                case "layerNameCounters": layerNameCounters = (System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.LayerNameCounter>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.LayerNameCounter>)); return true;
                case "nextCopyNumber": nextCopyNumber = reader.ReadInt(); return true;
                case "savedOutputSettings": savedOutputSettings = reader.ReadString(); return true;
                case "spriteSlices": spriteSlices = (System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.SpriteSlice>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.TextureCompositor.SpriteSlice>)); return true;
                case "width": width = reader.ReadInt(); return true;
                case "height": height = reader.ReadInt(); return true;
                case "outputFilter": outputFilter = reader.ReadEnum<UnityEngine.FilterMode>(); return true;
                case "uvReferenceMesh": uvReferenceMesh = (UnityEngine.Mesh)reader.ReadReference(); return true;
                case "uvReferenceChannel": uvReferenceChannel = reader.ReadInt(); return true;
                case "uvReferenceSubmesh": uvReferenceSubmesh = reader.ReadInt(); return true;
                case "layers": layers = (System.Collections.Generic.List<DCFApixels.WhimTex.Layer>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.Layer>)); return true;
                case "embeddedShaderFX": embeddedShaderFX = (System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFX>)reader.ReadList(typeof(System.Collections.Generic.List<DCFApixels.WhimTex.ShaderFX>)); return true;
            }
            return false;
        }
    }

}
